### ISSUE TITLE
remove  unnecessary files and folder

### ISSUE THREAD

**Issue by sms7182** [Inventory-System/Inventory-Management-System#15]
please remove bin and obj and debug folder from git @pedrampzh 
these file should not push to git

**Comment by sms7182** [comment]
please remove bin and obj and debug folder from git @HMoradiRad 
these file should not push to git

**Comment by sms7182** [comment]
please remove bin and obj and debug folder from git @Tayebe-Safari 
these file should not push to git

**Comment by HMoradiRad** [comment]
I've done the following

**Comment by HMoradiRad** [comment]
> 


> 
> 
> please remove bin and obj and debug folder from git @HMoradiRad
> these file should not push to git

I've done the following
