### ISSUE TITLE
New name for Project

### ISSUE THREAD

**Issue by Tayebe-Safari** [Inventory-System/Inventory-Management-System#20]
Hi, I Created a branch(Create Galaxy project), and I changed the name of project to Galaxy, I inserted new Base Classes and Purchase Classes,
please insert your own classes in this branch.
@pedrampzh @HMoradiRad

**Comment by HMoradiRad** [comment]
Hi,ok thanks ,then why not Sky.Business.Base?

**Comment by Tayebe-Safari** [comment]
One of the name was sugested, is galaxy.
