### ISSUE TITLE
Correct your fault on developing 

### ISSUE THREAD

**Issue by sms7182** [Inventory-System/Inventory-Management-System#3]
first error code:
  ` public abstract class BaseClass
    {
         public Guid id
         {
             get { return new Guid(); }
         }
        public int code { get; set; }
    }`
please try fix error in this code ... @Tayebe-Safari  and @HMoradiRad  and @pedrampzh

**Comment by Tayebe-Safari** [comment]
I fixed it ,
thanks for your attention
