### ISSUE TITLE
please clean your  code 

### ISSUE THREAD

**Issue by sms7182** [Inventory-System/Inventory-Management-System#4]
please PLEASE please  clean and try to professional :
`public class Company:Party
    {
        public string companyName{ get; set; }
        public string jobTitle { get; set; }
    }` this change to 
    public class Company:Party
    {
        public string CompanyName{ get; set; }
        public string JobTitle { get; set; }
    }
@HMoradiRad  and @Tayebe-Safari  and @pedrampzh  all Class:

**Comment by HMoradiRad** [comment]
Sorry, the request was made
